// All configuration constants and enums
module.exports = {
  STAGES: {
    ASK_LAST_MEAL: "askLastMeal",
    ASK_MOOD: "askMood",
    ASK_HEALTH_GOALS: "askHealthGoals",
    ORDER_ASK_WHAT: "orderAskWhat",
    ORDER_SELECT_RESTAURANT: "orderSelectRestaurant",
    ORDER_SELECT_COMBO: "orderSelectCombo",
    ORDER_ENTER_QTY: "orderEnterQty",
    ORDER_AWAIT_ADDRESS: "orderAwaitAddress",
    VENDOR_AWAIT_MENU: "vendorAwaitMenu",
    DRIVER_REG_AWAIT_PHOTO: "driverRegAwaitPhoto",
    DRIVER_AWAIT_VEHICLE_TYPE: "driverAwaitVehicleType",
    DRIVER_AWAIT_PHOTO: "driverAwaitPhoto",
  },

  STAGE_LABELS: {
    askLastMeal: "telling me what you last ate",
    askMood: "picking a mood",
    askHealthGoals: "sharing your health goals",
    orderAskWhat: "telling me what you want to order",
    orderSelectRestaurant: "picking a restaurant",
    orderSelectCombo: "picking a meal combo",
    orderEnterQty: "entering a quantity",
    orderAwaitAddress: "entering your delivery address",
    driverRegAwaitPhoto: "sending your rider photo",
    driverAwaitVehicleType: "picking your vehicle type",
  },

  MOOD_KEYWORDS: {
    light: "light",
    heavy: "heavy",
    filling: "heavy",
    healthy: "healthy",
    spicy: "spicy",
    pepper: "spicy",
    hot: "spicy",
    affordable: "affordable",
    budget: "affordable",
    cheap: "affordable",
    economy: "affordable",
    surprise: "surprise",
    anything: "surprise",
    whatever: "surprise",
    soup: "healthy",
    salad: "healthy",
    grilled: "healthy",
    protein: "healthy",
  },

  MOOD_CATALOG: {
    light: [
      {
        name: "Moi Moi & Pap",
        description: "Steamed bean pudding with fermented corn porridge",
        tags: ["Healthy", "Light", "Affordable"],
        kcal: 280,
      },
      {
        name: "Akara & Fried Plantain",
        description: "Crispy bean fritters with sweet fried plantain",
        tags: ["Light", "Affordable"],
        kcal: 310,
      },
      {
        name: "Grilled Fish Salad",
        description:
          "Grilled fish over a fresh salad with light Nigerian flavors",
        tags: ["Light", "Healthy"],
        kcal: 340,
      },
      {
        name: "Steamed Veg & Lean Protein",
        description: "Steamed vegetables with a lean protein of choice",
        tags: ["Healthy", "Light"],
        kcal: 320,
      },
      {
        name: "Fruit & Nut Bowl",
        description: "Fresh fruit and nut bowl with a ginger syrup drizzle",
        tags: ["Light", "Healthy"],
        kcal: 250,
      },
    ],
    heavy: [
      {
        name: "Pounded Yam & Egusi",
        description: "Rich, comforting egusi soup with pounded yam",
        tags: ["Heavy", "Filling"],
        kcal: 750,
      },
      {
        name: "Oha Soup & Fufu",
        description: "Wholesome oha soup with fufu and deep, savory flavor",
        tags: ["Heavy", "Filling"],
        kcal: 700,
      },
      {
        name: "Ogbono & Eba",
        description: "Thick ogbono soup with eba — very satisfying",
        tags: ["Heavy"],
        kcal: 680,
      },
      {
        name: "Fried Rice & Chicken Stew",
        description: "Loaded fried rice served with chicken stew",
        tags: ["Heavy", "Filling"],
        kcal: 620,
      },
      {
        name: "Suya Platter",
        description: "Bold, hearty suya platter with spicy beef",
        tags: ["Heavy", "Spicy"],
        kcal: 590,
      },
    ],
    healthy: [
      {
        name: "Grilled Fish & Greens",
        description: "Grilled fish with steamed greens — protein-rich",
        tags: ["Healthy"],
        kcal: 380,
      },
      {
        name: "Okra Soup & Light Swallow",
        description: "Okra soup with fish and a light swallow",
        tags: ["Healthy"],
        kcal: 420,
      },
      {
        name: "Boiled Plantain & Lean Stew",
        description: "Balanced, wholesome boiled plantain with lean stew",
        tags: ["Healthy"],
        kcal: 400,
      },
      {
        name: "Vegetable Soup & Lean Protein",
        description: "Fresh vegetable soup with a lean protein",
        tags: ["Healthy"],
        kcal: 410,
      },
      {
        name: "Fruit Bowl & Honey",
        description: "Natural, energizing fruit bowl with nuts and honey",
        tags: ["Healthy", "Light"],
        kcal: 260,
      },
    ],
    spicy: [
      {
        name: "Suya",
        description: "Smoky suya with onions and chili — a spicy classic",
        tags: ["Spicy"],
        kcal: 480,
      },
      {
        name: "Pepper Soup",
        description: "Hearty, warming pepper soup with meat",
        tags: ["Spicy", "Heavy"],
        kcal: 440,
      },
      {
        name: "Spicy Jollof Rice",
        description: "Bold, flavorful jollof rice with extra pepper",
        tags: ["Spicy"],
        kcal: 520,
      },
      {
        name: "Peppered Goat Meat",
        description: "Intensely flavored peppered goat meat",
        tags: ["Spicy", "Heavy"],
        kcal: 500,
      },
      {
        name: "Scotch Bonnet Stew",
        description: "Fiery hot stew with extra scotch bonnet pepper",
        tags: ["Spicy"],
        kcal: 460,
      },
    ],
    affordable: [
      {
        name: "Beans & Plantain",
        description: "Budget-friendly, filling beans with fried plantain",
        tags: ["Affordable", "Filling"],
        kcal: 450,
      },
      {
        name: "Fried Rice & Chicken",
        description: "Affordable, satisfying fried rice with chicken",
        tags: ["Affordable"],
        kcal: 560,
      },
      {
        name: "Akara & Bread",
        description: "Cheap and cheerful morning meal",
        tags: ["Affordable", "Light"],
        kcal: 340,
      },
      {
        name: "Yam Porridge",
        description: "Economical, tasty yam porridge with savory sauce",
        tags: ["Affordable"],
        kcal: 500,
      },
      {
        name: "Rice & Stew",
        description: "Classic, affordable rice and stew combo",
        tags: ["Affordable"],
        kcal: 530,
      },
    ],
  },

  ORDER_FILLER_PREFIXES: [
    "i would like to order",
    "i would like to",
    "i'd like to order",
    "i'd like to",
    "i want to order",
    "i want to",
    "can i order",
    "can i get",
    "please order",
    "let me order",
    "let me get",
    "i'll have",
    "ill have",
    "give me",
    "order",
  ],

  VEHICLE_TYPE_LABELS: {
    vehicle_bike: "Bike",
    vehicle_motorcycle: "Motorcycle",
    vehicle_bicycle: "Bicycle",
    vehicle_legedezbenz: "Legedezbenz",
    bike: "Bike",
    motorcycle: "Motorcycle",
    bicycle: "Bicycle",
    legedezbenz: "Legedezbenz",
  },

  ACTIVE_USER_WINDOW_MINUTES: 15,
};
